import type { Metadata } from "next";
import "./css/globals.css";

import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "FullStack AirPods - Apple (HK) -by Jimmy Lo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
